### PR TITLE
stuff for updating and renaming files

### PR DESCRIPTION
**Pull request by denzven**
added polar graphs and flat graphs...

### CODE REVIEW

**Comment by denzven** [comment]
pls correct js mistakes too

**Comment by Chandra-sekhar-pilla** [comment]
> pls correct js mistakes too

There are mistakes? In graph command or in others?

**Comment by denzven** [comment]
> 
> 
> > pls correct js mistakes too
> 
> There are mistakes? In graph command or in others?

well.. it works in my bot.. so.. jus recheck.. i have directly translated it from py to js

**Comment by Chandra-sekhar-pilla** [comment]
Oh ok i will change it

**Pull request merged**
